language: c

env:
  global:
    - OCTAVE=octave
    - OCTAVE_VER=4.4

matrix:
  include:
    - os: windows

install:
  - ./dev-tools/install-octave-windows.sh

script:
  - env
  - git config -l
  - PowerShell -Command 'Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*' | Select-Object DisplayName, DisplayVersion, Publisher, InstallDate | Format-Table -AutoSize'
  - PowerShell -Command 'Get-ItemProperty HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*' | Select-Object DisplayName, DisplayVersion, Publisher, InstallDate | Format-Table -AutoSize'
  - $OCTAVE --version
  - $OCTAVE --eval "ver"
  - $OCTAVE --eval 'disp("Hello, world!")'
