language: cpp

env:
  global:
    - OCTAVE=octave
    - OCTAVE_VER=4.4

matrix:
  include:
    - os: windows

install:
  - choco install make
  - choco install vcredist2010
  - ./dev-tools/install-octave-windows.sh
  # Enable running local PowerShell scripts
  - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'

script:
  - env
  - git config -l
  - make --version
  - choco list -l
  - PowerShell -Command 'Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName, DisplayVersion, Publisher, InstallDate | Format-Table -AutoSize'
  - PowerShell -Command 'Get-ItemProperty HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName, DisplayVersion, Publisher, InstallDate | Format-Table -AutoSize'
  - $OCTAVE --version
  - $OCTAVE --eval "ver"
  - $OCTAVE --eval 'disp("Hello, world!")'
  - dev-tools/diagnostics.bat
  - dev-tools/example_windows_script.bat
  - PowerShell -Command 'Get-Location'
  - PowerShell -File 'dev-tools\example_powershell_script.ps1'
  - $OCTAVE --version
  - $OCTAVE --eval "ver"
  - $OCTAVE --eval 'disp("Hello, world!")'
  - mkoctfile --version
